eclipse-jifa/jifa

- backend/build.gradle
- backend/common/build.gradle
[OWASP dependency-check](https://owasp.org/www-project-dependency-check/) shows issues with:
- vertx transitively:
- jackson: CVE-2020-24616, CVE-2019-14379, CVE-2019-14439, CVE-2019-14540, CVE-2019-14892, CVE-2019-14893, CVE-2019-16335, CVE-2019-16942, CVE-2019-16943, CVE-2019-17267, CVE-2019-17531, CVE-2019-20330, CVE-2020-10672, CVE-2020-10673, CVE-2020-10968, CVE-2020-10969, CVE-2020-11111, CVE-2020-11112, CVE-2020-11113, CVE-2020-11619, CVE-2020-11620, CVE-2020-14060, CVE-2020-14061, CVE-2020-14062, CVE-2020-14195, CVE-2020-24616, CVE-2020-8840, CVE-2020-9546, CVE-2020-9547, CVE-2020-9548
- netty: CVE-2019-20444, CVE-2019-20445, CVE-2020-11612
- log4j2: CVE-2020-9488
> Update vertx.io and log4j2 dependencies (security)

- NOTICE
- README.md
- backend/common/src/main/java/org/eclipse/jifa/common/JifaHooks.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/Constant.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/Global.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/Starter.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/support/FileSupport.java
- backend/worker/src/test/java/org/eclipse/jifa/worker/FakeHooks.java
- backend/worker/src/test/java/org/eclipse/jifa/worker/TestStarter.java
- frontend/public/config.js
- frontend/public/index.html
- frontend/src/Jifa.js
- frontend/src/components/menu/AnalysisResultMenu.vue
- frontend/src/components/menu/FinderMenu.vue
- frontend/src/components/menu/ViewMenu.vue
- frontend/src/config.js
- frontend/src/main.js
Provides a very basic customization layer for JIFA. This allows us to customize it for our deployments without carrying a fork of JIFA.
~~Build time configuration is available for the frontend:~~
Runtime configuration is available for the frontend:
- Disable/enable file management features of JIFA UI
Backend runtime hooks are provided for:
- Customize the HTTP server options
- Configure HTTP server routes to add authentication, error handling, health check URLs, etc.
- Customize the layout of heap files on the local file system.
> feat: Provide a basic customization option for JIFA deployments

- backend/worker/src/test/java/org/eclipse/jifa/worker/TestStarter.java
Switch to `undeploy()` and only do it if the verticle was deployed correctly. `close()` was causing some race-like issues.
Signed-off-by: Jason Koch <jkoch@netflix.com>
> fix: improve TestStarter tests to undeploy vs close the verticle

- backend/worker/src/main/java/org/eclipse/jifa/worker/route/FileRoute.java
Hi,
when transferByURL to upload dump file. if the url like:
https:/mydomain/dump-file/heap-2020-09-24_21_46_11-10.44.203.40_0470-xWfHPh16.hprof?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20201014T0631Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=JEB35GY4ZP8UUDOWKJ6Q%2F2020014%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=5aae4f2b1cb27f6b05aa6fa692c4f4d4fcfd1b6dda4d08c164466a877265bb
after extractFileName, we get the fileName: heap-2020-09-24_21_46_11-10.44.203.40_0470-xWfHPh16.hprof?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20201014T0631Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=JEB35GY4ZP8UUDOWKJ6Q%2F2020014%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=5aae4f2b1cb27f6b05aa6fa692c4f4d4fcfd1b6dda4d08c164466a877265bb
so can't make the …
> fix: extractFileName use url path instead of url.

- backend/worker/build.gradle
[CVE-2020-26939] Information Exposure in org.bouncycastle:bcprov-jdk15on, this updates transitivily to 1.66
> fix: upgrade sshj dependency to resolve CVE-2020-26939 transitive

- backend/worker/src/main/java/org/eclipse/jifa/worker/route/heapdump/DominatorTreeRoute.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/support/heapdump/HeapDumpSupport.java
- frontend/src/components/heapdump/DominatorTree.vue
Now we can't expand the children layer in dominater tree  like below:
so we want to figure out the chidren retained heap like below:
> feat: support get dominatorTree children groupBy class

- backend/worker/src/main/java/org/eclipse/jifa/worker/route/heapdump/HeapBaseRoute.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/route/heapdump/MergePathToGCRootsRoute.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/support/heapdump/HeapDumpSupport.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/vo/heapdump/gcrootpath/MergePathToGCRootsTreeNode.java
- frontend/src/components/heapdump/DynamicResultSlot.vue
- frontend/src/components/heapdump/HeapDump.vue
- frontend/src/components/heapdump/Histogram.vue
- frontend/src/i18n/cn.js
- frontend/src/i18n/en.js
We found something different when compare Jifa and Eclipse MAT about  pathToGCRoots in histogram view .
The root cause is Jifa use pathToGCRoot api but actually shoud use mergePathToGCRoots.
Jifa shows below:
Eclipse MAT shows below:
so, i think it's a bug need to fix.
After the fix shows below:
> fix: use mergePathToGCRoots instead of pathToGCRoot in histogram

- backend/common/src/main/java/org/eclipse/jifa/common/JifaHooks.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/Worker.java
In vertx 4.x migration, it indicates `ErrorHandler` requires `vertx` object passed in. In our case, we set up error handling during hooks stage, so we need the `vertx` object passed in.
https://vert-x3.github.io/vertx-4-migration-guide/index.html#changes-in-vertx-config_changes-in-common-components
> feat: expand hooks interface with vertx parameter, to support vertx 4.x change

- backend/common/src/main/java/org/eclipse/jifa/common/vo/support/SearchPredicate.java
This change ensures the Predicate is generated only once for the searchText/searchType, so that the regex parsing and string/double/long parsing occurs only once. Previously, this code generated a predicate that performed the switch, parsing, regex generation once for every value in the results to which the predicate was applied, which was a problem for very large results.
> Compile SearchPredicate once per search

- backend/common/src/main/java/org/eclipse/jifa/common/util/AccessorBasedTypeAdaptor.java
- backend/common/src/main/java/org/eclipse/jifa/common/util/TypeFactory.java
- backend/common/src/main/java/org/eclipse/jifa/common/util/UseAccessor.java
- backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java
- backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualDefaultItem.java
Current paging logic in `PageViewBuilder` enforces map -> filter -> sort -> paging output. This is correct since paging must occur after filter and sort, and filter and sort require data provided by map. But, it means any data collected during map phase is held for filter and sort, even if the data will be thrown away during paging (for ex, `label` is collected for _every_ item in dominatortree despite only 25 entries will show it).
This PR introduces a `VirtualDefaultItem` that acts like a `DefaultItem` but loads its contents on-demand from the results tree.  Results in significant 10x improvement on displaying DominatorTree for larger heaps.
--
- Also introduces GSON components to use getXxx() for parameters when `@UseAccessor` is added to a class. An alternative would be to use a …
> Collect DominatorTree item data only on-demand for paging

- frontend/src/components/heapdump/DominatorTree.vue
Fixes NullPointerException in DominatorTree view
Steps to reproduce:
1. open heapdump, go to DominatorTree
2. click Package view. Sort by '# Objects'.
3. click radio to change grouping to Object (NONE)
4. NPE is returned as backend cannot sort by Objects.
Fix:
Fixes this issue by resetting the sortBy if the grouping is changed to the NONE grouping.
> fix: NPE on DominatorTree when sorted by Objects and grouping NONE

- backend/heap-dump-analyzer/api/src/main/java/org/eclipse/jifa/hda/api/Model.java
- backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java
- frontend/src/components/heapdump/Thread.vue
In MAT the query dependency for `thread_info` now includes an extra field for Max Locals' Retained Heap that displays the max heap size for any locals present in the stack frame. We have to detect this situation and send back an appropriate result. In addition, we display it to the user. Not sortable as the value is only present for stack frames (not to the threads), so there is no sortable element at the top level.
More details here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572596
> feat: support MAT 572596 max locals retained heap in thread info view

- frontend/src/components/heapdump/HeapDump.vue
- frontend/src/components/heapdump/Query.vue
Support views setting up a new menu-item tab based on an oql or calcite sql query, for example (query over a specific component). Pass in a `queryType` and a `preparedQuery` and it will be executed immediately in `created()` callback. The ability to edit the query is disabled but you can copy the text.
```
<el-tab-pane name="nflxMetrics" lazy>
<span slot="label"> Atlas metrics </span>
<div v-bind:style="{ 'height': '100%', 'width': resultDivWidth}">
<Query :file="file"
queryType="sql"
@outgoingRefsOfObj="outgoingRefsOfObj"
@incomingRefsOfObj="incomingRefsOfObj"
@outgoingRefsOfClass="outgoingRefsOfClass"
@incomingRefsOfClass="incomingRefsOfClass"
@pathToGCRootsOfObj="pathToGCRootsOfObj"
@setSelectedObjectId="setSelectedObjectId"
preparedQuery='select m.name metric_name, count(*) …
```
> support prepared oql and calcite queries

- backend/common/src/main/java/org/eclipse/jifa/common/Constant.java
- backend/common/src/main/java/org/eclipse/jifa/common/ErrorCode.java
- backend/master/src/main/java/org/eclipse/jifa/master/Constant.java
- backend/master/src/main/java/org/eclipse/jifa/master/http/FileRoute.java
- backend/master/src/main/java/org/eclipse/jifa/master/http/UserRoute.java
- backend/master/src/main/java/org/eclipse/jifa/master/support/WorkerClient.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/route/FileRoute.java
- frontend/src/components/finder.vue
- frontend/src/components/menu/AnalysisResultMenu.vue
- frontend/src/i18n/cn.js
- frontend/src/i18n/en.js
Sometimes user want to read original file that was uploaded to to JIFA for some reason. This patch allows user to download the file, with size limit 512MB in master-worker mode and no limit in worker-only mode.
> feat: support downloading original file in full cluster mode

- backend/common/common.gradle
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832
> Bump log4j2 to 2.17.1

- backend/master/src/main/java/org/eclipse/jifa/master/http/UserRoute.java
Fix the problem that sometimes users can not download file if they don't enter jifa from the homepage. This is because the cookie is not on the path.
> fix: add authorization cookie path

- frontend/src/components/transferFile.vue
Add support for uploading with raw text. This is implemented by transforming raw text into a file in frontend and reuse the backend upload interface.
> feat: raw text upload support

- frontend/src/components/gclog/TimeLineChart.vue
Fix the problem of bumping echarts from ^4.6.0 to ^5.3.3
> fix: import echarts

- README.md
- backend/backend.gradle
- backend/heap-dump-analyzer/eclipse-mat-deps/eclipse-mat-deps.gradle
Need to upgrade the plugin 'com.diffplug.p2.asmaven', but this plugin requires JDK8...
See:
https://github.com/diffplug/goomph/blob/main/CHANGES.md#3291---2021-04-09
> [Heap Dump]: bump mat deps from 1.12.0 to 1.13.0

- backend/heap-dump-analyzer/api/src/main/java/org/eclipse/jifa/hda/api/HeapDumpAnalyzer.java
- backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java
- backend/worker/src/main/java/org/eclipse/jifa/worker/route/heapdump/HistogramRoute.java
- frontend/src/components/heapdump/DynamicResultSlot.vue
- frontend/src/components/heapdump/HeapDump.vue
- frontend/src/components/heapdump/Histogram.vue
this patch only fixes the problem when group_by = by_class
> fix: should list all instances of corresponding class when lookup inbound or outbound refs of histogram record (partially fixed)

- backend/worker/src/main/java/org/eclipse/jifa/worker/support/FileSupport.java
- frontend/src/components/transferFile.vue
iamrole instance based access will provide better security. Access keys and secret keys need not be shared to the user of jifa. It will provide more security over the s3 bucket by removing access key and secret key dependency
If access keys and secret key fails then it will automatically check for iamrole access. 
reference:  https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-access-s3-bucket/
> Added iamrole access support for accessing aws s3

- frontend/src/components/heapdump/Query.vue
This allows prepared query views to specify the query type (sql/oql) when passing the query
There are no existing in-tree users of prepared query views.
Allows passing of Calcite queries directly to a prepared query view, such as follows for showing atlas/spectator metrics.
```
<el-tab-pane name="atlasMetrics" lazy>
<span slot="label"> Atlas metrics </span>
<div v-bind:style="{ 'height': '100%', 'width': resultDivWidth}">
<Query :file="file"
queryType='sql'
@outgoingRefsOfObj="outgoingRefsOfObj"
@incomingRefsOfObj="incomingRefsOfObj"
@outgoingRefsOfClass="outgoingRefsOfClass"
@incomingRefsOfClass="incomingRefsOfClass"
@pathToGCRootsOfObj="pathToGCRootsOfObj"
@setSelectedObjectId="setSelectedObjectId"
preparedQueryType='sql'
preparedQuery='select m.name metric_name, count(*) metric_count …
```
> feat: specify query type for a prepared query view

- analysis/heap-dump/provider/src/main/java/org/eclipse/jifa/hdp/provider/HeapDumpAnalysisApiExecutor.java
- analysis/src/main/java/org/eclipse/jifa/analysis/AbstractApiExecutor.java
- frontend/src/components/Analysis.vue
- frontend/src/components/heapdump/Setup.vue
- frontend/src/components/heapdump/Toolbar.vue
- frontend/src/i18n/en.ts
- frontend/src/i18n/heapdump/en.ts
- frontend/src/i18n/heapdump/zh.ts
- frontend/src/i18n/zh.ts
- frontend/src/stores/analysis.ts
- frontend/vite.config.ts
Analyse could be faild caused by OOM(exceed limit of maximum length of array) if the dump file is very large. This problem can be solved by specify discard-object options. see: [Eclipse help](https://help.eclipse.org/latest/topic/org.eclipse.mat.ui.help/tasks/configure_mat.html#task_configure_mat__discard) .
Improve UI so user can specify those options.
before: dump analysis cache will dispose once user click 'Setting' button, it does not make sense.
now: dispose and re-analyse will performd sequencely only after use submit the new settings, but if user click the 'cancel' button after open the settins pannel, the pannel will closed and nothing else would happend.
> UI improvement, User can specify more options at memory dump analysis scene & changing setting is cancelable after open the settings pannel.

- analysis/gc-log/src/main/java/org/eclipse/jifa/gclog/fragment/Context.java
Current comparator neglected some conditions when two lines are equal, for example, both timestamps are not able to be parsed or both are recedent.
> fix: gc log sort

- frontend/src/components/jfr/Jfr.vue
hi all
Could I have a review of this patch. I would be very grateful.
If Thread /Class/Method name is truncated, now we can not see the full name.
This patch adds a tooltip to display the full name.
before the patch:
after the patch:
This patch also fixed another bug.
If dimension or filter-index(Thread/Class/Method) changed, clear the text of the Thread name input.
> bugfix: add tooltip to display full text (e.g. Method, Class, Thread)

- server/src/main/java/org/eclipse/jifa/server/Configuration.java
- server/src/main/java/org/eclipse/jifa/server/service/impl/K8SWorkerScheduler.java
- site/docs/guide/configuration.md
- site/docs/zh/guide/configuration.md
Hi, all
Could I have a review for this patch. I would be very grateful.
The official image is out of date, so I built an image and pushed it to our private registry, then found that it needs set pull secret to pull the elastic worker image from the private registry.
This patch adds the `image-pull-secret-name` option to the master node so that it can pull image from the private registry when scheduling a worker pod.
Thanks
> feature: add worker image pull secret name

- server/src/main/java/org/eclipse/jifa/server/Configuration.java
- server/src/main/java/org/eclipse/jifa/server/configurer/SecurityCryptoConfigurer.java
- server/src/main/java/org/eclipse/jifa/server/configurer/SecurityFilterConfigurer.java
- site/docs/guide/configuration.md
this allows a user to provide their own web filters by setting `jifa.security-filters-enabled: false`
the default is to have security filters enabled (ie: true)
> feat: add support to disable spring security web filters

- analysis/heap-dump/api/src/main/java/org/eclipse/jifa/hda/api/HeapDumpAnalyzer.java
- analysis/heap-dump/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java
- frontend/src/components/heapdump/EnvVariables.vue
- frontend/src/components/heapdump/HeapDump.vue
- frontend/src/i18n/heapdump/en.ts
- frontend/src/i18n/heapdump/zh.ts
feat: add a new tab for env variables in heapdump
> feat: add a new tab for env variables in heapdump

- server/src/main/java/org/eclipse/jifa/server/component/CurrentStaticWorker.java
Fix the problem that the static worker node obtains the loopback address as the IP address. I have tested this method on Linux and Windows and found no problems. However, I currently haven't found a good way to solve the problem of obtaining IP addresses under multiple network cards.
> fix: obtain the correct IP address for the static worker

- analysis/heap-dump/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualThreadItem.java
In the event that MAT does not return detailed thread information, it might return blank strings in the columns. Force-casting this to Boolean results in an Exception. Instead of throwing an Exception, we attempt to parse this to a Boolean which returns 'false' instead. It allows the data to be presented as false, which is incorrect, but the API is specified as `boolean`, so this is probably the best answer.
> fix: allow Threads view to show if MAT does not show it

- analysis/heap-dump/eclipse-mat-deps/eclipse-mat-deps.gradle
- analysis/heap-dump/hook/src/main/java/org/eclipse/mat/hprof/ui/HprofPreferences.java
Bump to Eclipse MAT 1.16.1 and update required dependencies, including Calcite plugin.
- New and Noteworthy 1.15.0 notes [here](https://eclipse.dev/mat/1.15.0/noteworthy.html)
- New and Noteworthy 1.16.0 notes [here](https://eclipse.dev/mat/1.16.0/noteworthy.html)
Full commit here -- https://github.com/eclipse-mat/mat/compare/R_1.14.0...R_1.16.1.
> Bump to Eclipse MAT 1.16.1
