eclipse-jifa/jifa

backend/worker/src/main/java/org/eclipse/jifa/worker/Starter.java
Unintentionally left a duplicate BodyHandler in the last PR #4 
Signed-off-by: Jason Koch <jkoch@netflix.com>
=> fix: remove duplicate BodyHandler

backend/worker/src/test/java/org/eclipse/jifa/worker/TestStarter.java
=> chore: have test cases occur on random port

backend/worker/src/test/java/org/eclipse/jifa/worker/route/FileRouteSuite.java, backend/worker/src/test/java/org/eclipse/jifa/worker/route/HeapDumpRouteSuite.java
Signed-off-by: Jason Koch <jkoch@netflix.com>
=> chore: add extra logging for failing test cases

backend/worker/build.gradle, backend/worker/src/main/java/org/eclipse/jifa/worker/route/FileRoute.java, backend/worker/src/main/java/org/eclipse/jifa/worker/support/FileSupport.java, frontend/src/components/transferFile.vue
Signed-off-by: yangdaotan <ydt64413394@aliyun.com>
=> feat: add S3 file transfer

backend/build.gradle
https://snyk.io/vuln/SNYK-JAVA-IONETTY-1020439
Signed-off-by: Jason Koch <jkoch@netflix.com>
=> bump netty-codec-http version to 4.1.53.Final for SNYK-JAVA-IONETTY-1020439

frontend/src/components/heapdump/Thread.vue
ThreadInfo gets stuck in fetching data, this trivial fix tries to address this problem.
=> fix: ThreadInfo stuck in fetching remote data

backend/worker/src/main/java/org/eclipse/jifa/worker/support/FileSupport.java
fix incorrect disk usage calculation
=> fix: incorrect disk usage calculation

backend/heap-dump-analyzer/eclipse-mat-deps/build.gradle
Fix: https://github.com/eclipse/jifa/issues/44
=> fix: build error of `./gradlew clean buildJifa`

backend/build.gradle, backend/heap-dump-analyzer/eclipse-mat-deps/build.gradle, backend/heap-dump-analyzer/impl/build.gradle, backend/worker/src/main/java/org/eclipse/jifa/worker/support/Analyzer.java
=> Eclipse 1.12 and Java 11 support

frontend/src/components/transferFile.vue
Enable local file uploading as default
=> feat: enable local file uploading as default

backend/build.gradle, backend/master/src/main/java/org/eclipse/jifa/master/http/FileRoute.java, backend/master/src/main/java/org/eclipse/jifa/master/service/impl/FileServiceImpl.java, backend/master/src/main/java/org/eclipse/jifa/master/vo/ExtendedFileInfo.java, demo/demo.sql, frontend/src/components/menu/AnalysisResultMenu.vue, frontend/src/i18n/cn.js, frontend/src/i18n/en.js
feat: unlock file while analyzing or inspecting
Signed-off-by: Yi Yang <qingfeng.yy@alibaba-inc.com>
=> feat: unlock file while analyzing or inspecting

frontend/src/config.js
Signed-off-by: Yi Yang <qingfeng.yy@alibaba-inc.com>
=>  fix: set workerOnly as default value

frontend/src/components/menu/AnalysisResultMenu.vue
Signed-off-by: Yi Yang <qingfeng.yy@alibaba-inc.com>
=> fix: disable unlock button after unlocked

backend/worker/build.gradle
Resolves
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35491
=> Upgrade to latest aws-java-sdk to pick up latest jackson-databind

backend/heap-dump-analyzer/api/src/main/java/org/eclipse/jifa/hda/api/Model.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualThreadItem.java
Supports lazy loading for thread UI elements; improves the performance of the thread page.
=> perf: lazy load Thread items from MAT

backend/master/src/main/java/org/eclipse/jifa/master/task/DiskCleaningTask.java
fix: possible mad loop to execute disk cleanup too many times
=> fix: possible mad loop to execute disk cleanup too many times

backend/common/src/main/java/org/eclipse/jifa/common/util/PageViewBuilder.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java
please help review this change that fixes the sorting problem that exists in QOL.
=> fix: OQL result sorting problem

backend/heap-dump-analyzer/eclipse-mat-deps/build.gradle
=> refine: maybe faster Mat Calcite plugin download site

backend/common/src/main/java/org/eclipse/jifa/common/cache/Cache.java, backend/worker/src/main/java/org/eclipse/jifa/worker/Constant.java, backend/worker/src/main/java/org/eclipse/jifa/worker/WorkerGlobal.java, backend/worker/src/main/java/org/eclipse/jifa/worker/support/Analyzer.java, backend/worker/src/main/resources/worker-config.json
=> fix: Cache can not be clear automatically

backend/worker/src/main/java/org/eclipse/jifa/worker/Worker.java, backend/worker/src/main/java/org/eclipse/jifa/worker/WorkerGlobal.java, backend/worker/src/test/java/org/eclipse/jifa/worker/TestWorker.java
a fix for https://github.com/eclipse/jifa/issues/84
=> test: fix worker test failure

frontend/src/components/menu/AnalysisResultMenu.vue
Please review this minor fix that adds a missing param to the request. Thanks.
=> fix: missing type param

backend/common/src/main/java/org/eclipse/jifa/common/util/EscapeUtil.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/HeapDumpAnalyzerImpl.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualClassItem.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualClassLoaderItem.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualDefaultItem.java, backend/heap-dump-analyzer/impl/src/main/java/org/eclipse/jifa/hda/impl/VirtualPackageItem.java
Unescape unicode string label to string
=> fix: unescape unicode string label to string

.github/workflows/check_pr.yml
=> build: add workflows

backend/worker/worker.gradle
change
```
DEFAULT_JVM_OPTS='"-Dmat-deps=${APP_HOME}/mat-deps"'
```
to 
```
DEFAULT_JVM_OPTS=-Dmat-deps=${APP_HOME}/mat-deps
```
=> fix: deploy_worker.sh  failed to run

backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/model/GCDiagnoser.java, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/model/GCEvent.java, frontend/src/i18n/cn.js, frontend/src/i18n/en.js
This patch will give a warning when we detect that young generation of g1 suddenly becomes small in gclog.
=> feat: gclog diagnose that young gen becomes very small

README.md
Adds a note to the quick demo section for people attempting the demo on an M1 chip.
=> Add M1 note to demo section

backend/gc-log-analyzer/README.md, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/event/evnetInfo/GCCause.java, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/event/evnetInfo/GCEventBooleanType.java, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/model/G1GCModel.java, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/model/GenerationalGCModel.java, backend/gc-log-analyzer/src/main/java/org/eclipse/jifa/gclog/parser/JDK8GenerationalGCLogParser.java, backend/gc-log-analyzer/src/test/java/org/eclipse/jifa/gclog/TestParser.java, frontend/src/components/gclog/GCLog.vue, frontend/src/components/gclog/GCLogUtil.js
feat: reset config model when showCompareConfig
fix: remove rebuild RS in jdk8 g1
feat: improve support for promotion failed
feat: update README for GC Log
=> Some fix and improvement for GC Log Analysis

backend/worker/src/main/java/org/eclipse/jifa/worker/support/FileSupport.java, frontend/src/components/transferFile.vue
Fixed this issue as I really need it to work and now it works
=> Fixed s3 upload issue 

deploy/default_pattern/docker-compose.yml
modify the command of docker-compose.yml，make happy test~
=> fix: modify command of docker-compose.yml

analysis/gc-log/src/main/java/org/eclipse/jifa/gclog/fragment/GCModelConverter.java
add new label filed `type` for gc metric `GC_COST_TIME`
=> feat: add new label for gc metrics

manifests/README.md, manifests/charts/jifa/.helmignore, manifests/charts/jifa/Chart.yaml, manifests/charts/jifa/templates/NOTES.txt, manifests/charts/jifa/templates/_helpers.tpl, manifests/charts/jifa/templates/hpa.yaml, manifests/charts/jifa/templates/ingress.yaml, manifests/charts/jifa/templates/jifa-configmap.yaml, manifests/charts/jifa/templates/jifa-master-deployment.yaml, manifests/charts/jifa/templates/jifa-pvc.yaml, manifests/charts/jifa/templates/jifa-service.yaml, manifests/charts/jifa/templates/mysql-deployment.yaml, manifests/charts/jifa/templates/mysql-pvc.yaml, manifests/charts/jifa/templates/mysql-service.yaml, manifests/charts/jifa/templates/role.yaml, manifests/charts/jifa/templates/rolebinding.yaml, manifests/charts/jifa/templates/serviceaccount.yaml, manifests/charts/jifa/values.yaml
@D-D-H I accidentally merged my other modifications into it this morning, so I closed the previous PR( #268  )
=> feat: jifa helm charts

server/src/main/java/org/eclipse/jifa/server/controller/AnalysisApiStompController.java
allow integration to different spring security providers
=> refactor: stomp ApiStompController to stash a more general auth value

frontend/src/components/heapdump/Threads.vue
=> feat: allow sort by Name in heapdump Threads view

analysis/gc-log/src/main/java/org/eclipse/jifa/gclog/model/GCModel.java
https://github.com/eclipse/jifa/issues/282
=> update start time stamp in autoDecideStartEndTime

frontend/src/components/gclog/TimeGraph.vue
=> fix: missing timegraph for gc analysis on legend selection change
